apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: demo-service

spec:
  type: service
  owner: rde-dev-team
  system: demo-system
  lifecycle: production
  providesApis:
    - demo-api
