apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: demo-service
  description: "Dịch vụ dùng để demo Global Map"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: rde-dev-team
  system: demo-system
  lifecycle: production
  providesApis:
    - demo-api
